# use shift + enter to execute a statement

In [1]:
import numpy as np

In [2]:
myarr=np.array([1,2,3,4])  #this is a numpy array     #this is first way of creating numpy array i.e. from python list

In [3]:
myarr

array([1, 2, 3, 4])

In [4]:
myarr.shape

(4,)

In [5]:
myarr.dtype

dtype('int32')

In [6]:
myarr[1]

2

In [7]:
myarr1=np.array([[1,2,3,4]])    #now this is a two dimentional array

In [8]:
myarr1.shape

(1, 4)

In [9]:
myarr1[0,1]

2

# 5 general mechanisms to create numpy array

# 1) Conversion from other Python structures (e.g., lists, tuples)

In [10]:
listarray=np.array([[1,2,3],[4,5,6],[7,8,9]])
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
listarray.shape

(3, 3)

In [12]:
listarray.dtype

dtype('int32')

In [13]:
listarray.size

9

# 2) Intrinsic numpy array creation objects (e.g., arange, ones, zeros, etc.)

In [14]:
zeros= np.zeros((2,5))     # it will form an array of zeroes
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
zeros.shape

(2, 5)

In [16]:
rng=np.arange(15)     # it will form an array of elements starting from 0 upto the number we input in parenthesis
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
lspace= np.linspace(1,50,10)   #it will put equally spaced 10 elements between 1 and 50 in an array
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [18]:
emp=np.empty((4,6))    #it will create an empty array with random values
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.06811354e-306, 1.15710971e-306, 1.42419938e-306],
       [7.56603881e-307, 7.56600486e-307, 1.02360867e-306,
        2.00270228e-307, 1.78019082e-306, 1.11256817e-306],
       [1.06811422e-306, 1.42417221e-306, 1.11260619e-306,
        8.90094053e-307, 1.86919378e-306, 1.06809792e-306],
       [1.37962456e-306, 1.69111861e-306, 1.78020169e-306,
        1.37961777e-306, 7.56599807e-307, 5.33590898e-322]])

In [19]:
emp_like=np.empty_like((lspace))    #it will create an empty array with size equal to that of lspace
emp_like

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [20]:
ide=np.identity(45)    #it will create a identity matrix of size 45
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [21]:
arr=np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [22]:
arr.shape


(99,)

In [23]:
arr=arr.reshape(3,33)  #it will reshape arr

In [24]:
arr


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [25]:
arr=arr.ravel()     #it will convert arr into 1-D array again
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [27]:
arr.shape

(99,)

In [28]:
x = [[1,2,3],[4,5,6],[7,8,9]]
x

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [29]:
ar=np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
ar.sum()   #sum of all elements

45

In [31]:
ar.sum(axis=0)   #sum of all rows

array([12, 15, 18])

In [32]:
ar.sum(axis=1)   #sum of all columns

array([ 6, 15, 24])

In [33]:
ar.T      #it will give the transpose of the array

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [34]:
ar.ndim    #it will give the no of dimentions of the array

2

In [35]:
ar.size     #it will give the no of elements in the array

9

In [36]:
ar.nbytes

36

In [37]:
one=np.array([1,3,789,52,0])
one

array([  1,   3, 789,  52,   0])

In [38]:
one.argmax()    #it will give the index of the maximum element of the array

2

In [39]:
one.argmin()    #it will give the index of minimum element of the array

4

In [40]:
arr2=np.array([[9,8,7],[6,5,4],[3,2,1]])
arr2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [41]:
arr+arr2

ValueError: operands could not be broadcast together with shapes (99,) (3,3) 

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [43]:
ar+arr2   #matrix addition

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [44]:
ar*arr2     #matrix multiplication

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

In [45]:
np.sqrt(arr2)    #gives square root of all elements of array

array([[3.        , 2.82842712, 2.64575131],
       [2.44948974, 2.23606798, 2.        ],
       [1.73205081, 1.41421356, 1.        ]])

In [46]:
arr2.sum()

45

In [47]:
arr2.max()

9

In [48]:
arr2.min()

1

In [49]:
np.count_nonzero(arr2)     #counts the nonzero elements of the array

9

In [50]:
arr2.tolist()  #it will return the list of an array

[[9, 8, 7], [6, 5, 4], [3, 2, 1]]

In [51]:
ar.sort()

In [52]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
arr2=np.array(arr2)

In [54]:
arr2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [55]:
arr2.sort(axis=1)
arr2

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])